repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: [--strict]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.5    # or the appropriate tag from this repo
    hooks:
      - id: ruff
        args: [
                "--select=All",
                "--ignore",
                "--fix",
                "--line-length=120",
                "--preview",
        ]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        stages: [ pre-commit, pre-push ]

